'use strict';
const $ = id => document.getElementById(id);
const escapeHTML = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels = {ready:'等待开始',starting:'启动中',loading:'载入工程',rendering:'正在渲染',pausing:'等待当前帧保存',watching:'等待完整 PNG',paused:'已暂停 · 资源已释放',finishing:'正在退出进程',complete:'全部完成',interrupted:'已中断 · 可继续',error:'发生错误'};
let token = new URLSearchParams(location.hash.slice(1)).get('token') || sessionStorage.getItem('renderdesk-token') || '';
if(location.hash) history.replaceState(null,'',location.pathname);
let snapshot = {tasks:[],processes:[],system:{}}, selected = null, cursor = -1, logGeneration = 0, attachProcess = null, polling = false, settingsLoaded = false;
let toastTimer;
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,5000);}
function duration(seconds){if(seconds==null)return '—';seconds=Math.max(0,Math.floor(seconds));return `${Math.floor(seconds/3600).toString().padStart(2,'0')}:${Math.floor(seconds/60)%60}`.replace(/:(\d)$/,':0$1')+':'+String(seconds%60).padStart(2,'0');}
const number=(value,unit='')=>value==null?'—':Number(value).toFixed(1)+unit;
async function api(path,body){const r=await fetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});const data=await r.json();if(r.status===401){sessionStorage.removeItem('renderdesk-token');if(!$('login').open)$('login').showModal();throw Error('请输入有效访问密钥');}if(!r.ok)throw Error(data.error||'请求失败');return data;}
async function command(action,values={}){const {operation}=await api('commands',{action,values});for(let i=0;i<900;i++){await new Promise(resolve=>setTimeout(resolve,300));const result=await api('operations/'+operation);if(result.done){if(result.error)throw Error(result.error);await poll();return result.result;}}throw Error('操作仍在后台处理，请刷新查看状态，不要重复提交。');}
function guard(fn){return async event=>{const button=event?.submitter||event?.currentTarget;const disable=button?.tagName==='BUTTON';if(disable)button.disabled=true;try{await fn(event);}catch(error){toast(error.message);}finally{if(disable)button.disabled=false;renderDetail();}};}
function setView(view){for(const v of ['tasks','processes','settings'])$(v+'-view').hidden=v!==view;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const titles={tasks:['渲染工作台','让渲染继续，也给生活留一点时间。'],processes:['本机进程','把藏在后台的渲染，看清楚、管起来。'],settings:['软件设置','无论在哪，都能知道渲染进行到了哪里。']};$('page-title').textContent=titles[view][0];$('page-description').textContent=titles[view][1];if(view==='settings')loadSettings().catch(e=>toast(e.message));}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));
function taskMarkup({job:j,status:s}){const percent=Math.min(100,Math.round(100*s.done/(s.total||1)));return `<article class="task-card ${selected===j.id?'selected':''}" tabindex="0" role="button" data-task="${escapeHTML(j.id)}" aria-label="选择 ${escapeHTML(j.name)}"><div class="task-top"><div><div class="task-name">${escapeHTML(j.name)}</div><div class="task-path" title="${escapeHTML(j.blend)}">${escapeHTML(j.blend)}</div></div><span class="badge ${s.state==='error'?'error':''}">${escapeHTML(labels[s.state]||s.state)}</span></div><div class="task-metrics"><span><b>${s.done} / ${s.total}</b> 帧 · ${percent}%</span><span>用时 <b>${duration(s.elapsed)}</b></span><span>CPU <b>${number(s.cpu,'%')}</b></span><span>内存 <b>${number(s.ram_mb,' MB')}</b></span><span>GPU <b>${number(s.gpu,'%')}</b></span><span>显存 <b>${number(s.vram_mb,' MB')}</b></span></div><div class="progress"><i style="width:${percent}%"></i></div></article>`;}
function render(){const tasks=snapshot.tasks;let running=tasks.filter(t=>t.status.running).length;const done=tasks.reduce((n,t)=>n+t.status.done,0),total=tasks.reduce((n,t)=>n+t.status.total,0);$('task-count').textContent=tasks.length;$('running').innerHTML=running+'<small>个任务</small>';$('frames').innerHTML=done+'<small>/ '+total+'</small>';$('cpu').innerHTML=number(snapshot.system.cpu)+'<small>%</small>';$('memory').innerHTML=number(snapshot.system.ram_used)+`<small>/ ${number(snapshot.system.ram_total)} GB</small>`;$('queue-summary').textContent=tasks.length+' 个任务 · '+running+' 个运行中';
const list=$('tasks'), previousScroll=list.scrollTop;const cards=tasks.map(taskMarkup).join('');if(!tasks.length){list.innerHTML='<div class="empty"><div class="symbol">◈</div><h3>从一帧灵感开始</h3><p>添加 Blender 工程，让后台渲染有一个看得见的工作台。</p><button class="primary" id="empty-add">＋ 添加第一个任务</button></div>';$('empty-add').onclick=()=>openTask();}else{for(const t of tasks){let card=list.querySelector(`[data-task="${CSS.escape(t.job.id)}"]`);const html=taskMarkup(t);if(!card){if(list.querySelector('.empty'))list.textContent='';list.insertAdjacentHTML('beforeend',html);}else if(card.outerHTML!==html){const focused=document.activeElement===card;card.outerHTML=html;if(focused)list.querySelector(`[data-task="${CSS.escape(t.job.id)}"]`).focus({preventScroll:true});}}}list.scrollTop=previousScroll;
$('processes').innerHTML=snapshot.processes.map(p=>{const managed=tasks.find(t=>t.status.pid===p.pid);return `<tr><td>${escapeHTML(p.blend.split(/[\\/]/).pop()||'Blender')}<small>PID ${p.pid}</small></td><td>${duration(p.elapsed)}</td><td>${number(p.cpu,'%')}</td><td>${number(p.ram_mb,' MB')}</td><td>${number(p.gpu,'%')}<small>${number(p.vram_mb,' MB')}</small></td><td><button data-process="${p.pid}" ${managed?'disabled':''}>${managed?'已管理':'接入任务'}</button></td></tr>`;}).join('')||'<tr><td colspan="6" class="muted">暂未发现运行中的 Blender 进程。</td></tr>';
const notices=snapshot.notices||[];$('notice').hidden=!notices.length;$('notice').textContent=notices.join(' · ');renderDetail();if(snapshot.bark){const status={pending:'等待发送 / 重试中',sent:'最近一条通知已发送',failed:'最近一条通知失败（已尝试 3 次）'};$('bark-status').textContent=(status[snapshot.bark.last_status]||'尚无通知记录')+'。通知需要管理服务保持运行。';}}
function selectTask(id){selected=id;cursor=-1;logGeneration++;$('log').textContent='';render();pollLog();}
$('tasks').onclick=e=>{const card=e.target.closest('[data-task]');if(card)selectTask(card.dataset.task);};$('tasks').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){const card=e.target.closest('[data-task]');if(card){e.preventDefault();selectTask(card.dataset.task);}}};
function renderDetail(){const t=snapshot.tasks.find(t=>t.job.id===selected);for(const id of ['start','pause','schedule','copy-output','rescan'])$(id).disabled=!t;updatePreview(t);if(!t)return;const j=t.job,s=t.status;$('rescan').disabled=s.running&&j.external?.phase!=='attached';$('detail-title').textContent=j.name;$('detail-state').textContent=labels[s.state]||s.state;$('start').disabled=s.running;$('pause').disabled=!s.running;$('detail-info').textContent=`${s.done} / ${s.total} 帧 · 当前帧 ${s.frame??'—'} · 累计 ${duration(s.elapsed)} · 预计剩余 ${duration(s.eta)}\n工程范围：${j.project?j.project.start+'–'+j.project.end+'，共 '+j.project.total+' 帧':'尚未扫描，可重新扫描工程'} · 本次范围：${j.start}–${j.end}（${j.range_source==='override'?'手动覆盖':j.range_source==='project'?'读取工程':'旧版设置'}）\n输出：${j.output}`+(s.recovery?.due?' · 将于 '+new Date(s.recovery.due*1000).toLocaleTimeString()+' 自动恢复':'')+(s.recovery?.attempts?' · 已自动恢复 '+s.recovery.attempts+' 次':'')+(s.recovery?.error?' · 恢复失败：'+s.recovery.error:'')+(s.message?' · '+s.message:'')+(j.start_at?' · 计划开始 '+new Date(j.start_at*1000).toLocaleString():'')+(j.pause_at?' · 计划暂停 '+new Date(j.pause_at*1000).toLocaleString():'');}
async function pollLog(){if(!selected)return;const id=selected,generation=logGeneration;const result=await api('jobs/'+encodeURIComponent(id)+'/log?cursor='+cursor);if(id!==selected||generation!==logGeneration)return;cursor=result.cursor;const log=$('log');if(result.reset)log.textContent='';if(result.text)log.textContent=(log.textContent+result.text).slice(-160000);if($('follow').checked)log.scrollTop=log.scrollHeight;}
async function poll(){if(polling||!token)return;polling=true;try{snapshot=await api('state');sessionStorage.setItem('renderdesk-token',token);$('connection').textContent='服务已连接 · 实时更新';if($('login').open)$('login').close();if(!selected&&snapshot.tasks.length)selectTask(snapshot.tasks[0].job.id);render();await pollLog();document.documentElement.dataset.ready='true';}catch(error){$('connection').textContent='连接中断 · 自动重连';}finally{polling=false;}}
$('login-form').onsubmit=async e=>{e.preventDefault();token=$('access-key').value.trim();try{await api('state');$('login-error').textContent='';await poll();}catch(error){$('login-error').textContent=error.message;}};
$('refresh').onclick=guard(async()=>{await command('refresh');toast('列表已刷新');});$('start').onclick=guard(()=>command('start',{id:selected}));$('pause').onclick=guard(async()=>{await command('pause',{id:selected});toast('已请求暂停，等待当前帧完整保存。');});
async function copy(value){try{await navigator.clipboard.writeText(value);toast('已复制');}catch{const input=document.createElement('textarea');input.value=value;document.body.append(input);input.select();const ok=document.execCommand('copy');input.remove();if(!ok)throw Error('浏览器不允许复制，请使用 HTTPS 或在桌面端复制');toast('已复制');}}
$('copy-output').onclick=guard(()=>copy(snapshot.tasks.find(t=>t.job.id===selected).job.output));$('clear-log').onclick=()=>{$('log').textContent='';};
async function loadSettings(){const data=await api('settings');$('bark-enabled').checked=data.bark.enabled;$('bark-configured').textContent=data.bark.configured?'已保存推送地址；留空保留原地址':'尚未配置';$('remote-enabled').checked=data.remote_next;$('remote-port').value=data.port;$('remote-status').textContent=data.remote?'当前允许局域网访问；所有操作均需访问密钥。':'当前仅本机访问。启用并重启后可从局域网连接。';settingsLoaded=true;renderSettings(data);return data;}
$('bark-form').onsubmit=guard(async e=>{e.preventDefault();await command('bark.save',{enabled:$('bark-enabled').checked,url:$('bark-url').value.trim()});$('bark-url').value='';await loadSettings();toast('通知设置已保存');});$('bark-test').onclick=guard(async()=>{await command('bark.test');toast('测试通知已进入发送队列');});
$('remote-form').onsubmit=guard(async e=>{e.preventDefault();const r=await api('remote',{enabled:$('remote-enabled').checked,port:Number($('remote-port').value)});toast(r.message);});$('copy-key').onclick=guard(async()=>copy((await api('access')).token));
let scans = [], scanning = false;
function sceneFor(scan, card){return scan.scenes.find(s=>s.scene===card.querySelector('[data-scene]').value);}
function scanMarkup(scan, index){if(scan.error)return `<article class="scan-card scan-error"><h3>${escapeHTML(scan.path)}</h3><p>${escapeHTML(scan.error)}</p></article>`;return `<article class="scan-card" data-scan="${index}"><h3>${escapeHTML(scan.blend.split(/[\\/]/).pop())}</h3><label>场景<select data-scene>${scan.scenes.map(s=>`<option ${s.scene===scan.active_scene?'selected':''}>${escapeHTML(s.scene)}</option>`).join('')}</select></label><p class="scan-meta"></p><label class="check-row"><input type="checkbox" data-override> 手动覆盖帧范围 / 输出目录</label><fieldset data-overrides disabled><div class="form-grid"><label>起始帧<input data-start type="number" required></label><label>结束帧<input data-end type="number" required></label><label>步长<input data-step type="number" min="1" required></label></div><label>输出文件夹<input data-output placeholder="留空沿用工程路径"></label></fieldset>${scan.process?'<label>实际 PNG 输出目录<input data-attach-output required></label><label>实际 PNG 文件名模板<input data-pattern required value="####.png"></label><p class="help">已读取磁盘工程范围。脚本可能在内存中修改输出，请核对以上目录及模板；若脚本只渲染部分帧，请勾选覆盖范围。</p>':'<label class="check-row"><input type="checkbox" data-autoexec> 允许可信工程自动执行 Python</label>'}</article>`;}
function fillScene(card, scan){const s=sceneFor(scan,card);card.querySelector('.scan-meta').textContent=`${s.start}–${s.end} 帧 · 步长 ${s.step} · 共 ${s.total} 帧\n${s.engine} · ${s.resolution_x} × ${s.resolution_y} · ${s.resolution_percentage}% · ${s.format} ${s.color_depth}bit\n相机：${s.camera||'未指定'}\n输出：${s.first_output}\n默认沿用工程设置，不修改工程文件。`;for(const k of ['start','end','step'])card.querySelector('[data-'+k+']').value=s[k];card.querySelector('[data-output]').value='';if(scan.process){const file=s.first_output.split(/[\\/]/).pop(),folder=s.first_output.slice(0,-file.length);card.querySelector('[data-attach-output]').value=folder;card.querySelector('[data-pattern]').value=file.replace(/-?\d+(?=\.[^.]+$)/,m=>'#'.repeat(m.length));}}
async function openTask(process=null, paths=[]){attachProcess=process;scans=[];$('scan-results').textContent='';$('import-projects').disabled=true;$('project-paths').value=paths.join('\n');$('new-fields').hidden=!!process;$('task-dialog-title').textContent=process?'接入进程 · PID '+process.pid:'添加工程';$('task-help').textContent=process?'先读取该进程使用的工程，再确认实际输出位置。':'支持批量导入；默认使用全局 Blender 版本并沿用工程配置。';const settings=await api('settings');$('task-blender').innerHTML=settings.blenders.items.map(i=>`<option value="${i.id}" ${i.id===settings.blenders.default?'selected':''}>${escapeHTML(i.name)}${i.id===settings.blenders.default?' · 默认':''}</option>`).join('');$('pick-projects').hidden=!window.pywebview;$('scan-status').textContent='扫描不修改 .blend 文件';if(!$('task-dialog').open)$('task-dialog').showModal();if(process)await scanProjects();}
async function scanProjects(){if(scanning)return;scanning=true;$('scan-projects').disabled=true;$('import-projects').disabled=true;$('scan-results').textContent='';scans=[];try{const paths=attachProcess?[null]:[...new Set($('project-paths').value.split(/\r?\n/).map(p=>p.trim().replace(/^"|"$/g,'')).filter(Boolean))];if(!paths.length)throw Error('请先选择或拖入工程');if(paths.length>32)throw Error('单次最多导入 32 个工程');for(let i=0;i<paths.length;i++){$('scan-status').textContent=`正在读取 ${i+1} / ${paths.length}，可继续查看后台任务…`;let result;try{result=await command('project.scan',attachProcess?{process:attachProcess}:{path:paths[i],blender_id:$('task-blender').value});}catch(error){result={error:error.message,path:paths[i]||'当前进程'};}scans.push(result);$('scan-results').insertAdjacentHTML('beforeend',scanMarkup(result,i));const card=$('scan-results').querySelector(`[data-scan="${i}"]`);if(card)fillScene(card,result);}$('scan-status').textContent=`已读取 ${scans.filter(s=>!s.error).length} / ${paths.length} 个工程`;$('import-projects').disabled=!scans.some(s=>!s.error);}finally{scanning=false;$('scan-projects').disabled=false;}}
$('scan-results').onchange=e=>{const card=e.target.closest('[data-scan]');if(!card)return;const scan=scans[Number(card.dataset.scan)];if(e.target.matches('[data-scene]'))fillScene(card,scan);if(e.target.matches('[data-override]'))card.querySelector('[data-overrides]').disabled=!e.target.checked;};
$('new-task').onclick=guard(()=>openTask());$('drop-hint').onclick=guard(()=>openTask());$('scan-projects').onclick=guard(scanProjects);
$('processes').onclick=guard(async e=>{const b=e.target.closest('[data-process]');if(b)await openTask(snapshot.processes.find(p=>p.pid===Number(b.dataset.process)));});
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
$('pick-projects').onclick=guard(async()=>{const paths=await window.pywebview.api.pick('blend');if(paths)$('project-paths').value=[...new Set([...$('project-paths').value.split('\n').filter(Boolean),...paths])].join('\n');});
window.receiveDroppedProjects=async paths=>{document.body.classList.remove('dragging');if(scanning){toast('正在扫描，请在扫描结束后添加更多工程');return;}try{await openTask(null,paths);}catch(error){toast(error.message);}};
document.addEventListener('dragover',e=>{e.preventDefault();document.body.classList.add('dragging');});document.addEventListener('dragleave',e=>{if(!e.relatedTarget)document.body.classList.remove('dragging');});document.addEventListener('drop',e=>{e.preventDefault();document.body.classList.remove('dragging');if(window.pywebview)return;const text=e.dataTransfer.getData('text/plain');if(text)window.receiveDroppedProjects(text.split(/\r?\n/).filter(Boolean));else toast('网页端请填写渲染电脑上的工程路径；桌面端支持拖入本机文件。');});
$('task-form').onsubmit=guard(async e=>{e.preventDefault();let created=0,lastId=null;for(const card of $('scan-results').querySelectorAll('[data-scan]:not(.done)')){const scan=scans[Number(card.dataset.scan)],overrides={autoexec:!!card.querySelector('[data-autoexec]')?.checked};if(card.querySelector('[data-override]').checked){overrides.range={};for(const k of ['start','end','step'])overrides.range[k]=Number(card.querySelector('[data-'+k+']').value);overrides.output=card.querySelector('[data-output]').value.trim();}const values={scan_id:scan.scan_id,scene:card.querySelector('[data-scene]').value,overrides};if(scan.process){values.output=card.querySelector('[data-attach-output]').value.trim();values.pattern=card.querySelector('[data-pattern]').value.trim();}try{lastId=await command('project.import',values);created++;card.classList.add('done');card.querySelectorAll('input,select').forEach(i=>i.disabled=true);}catch(error){toast(`${scan.blend.split(/[\\/]/).pop()}：${error.message}`);return;}}if(created){$('task-dialog').close();setView('tasks');selectTask(lastId);toast(`已添加 ${created} 个任务`);}});
$('rescan').onclick=guard(async()=>{const id=selected;await command('project.rescan',{id});toast('已重新读取工程范围，完成帧和日志保留');});
let previewKey='',previewURL='',previewBusy=false;
async function updatePreview(t){const latest=t?.status.latest;const key=t&&latest?t.job.id+':'+latest.version:'';if(!key){$('preview').hidden=true;$('preview-empty').hidden=false;$('preview-caption').textContent='完成第一帧后自动显示';previewKey='';return;}if(key===previewKey||previewBusy)return;previewBusy=true;previewKey=key;$('preview-caption').textContent='正在载入最新完整帧…';try{const r=await fetch('/api/jobs/'+t.job.id+'/preview',{headers:{Authorization:'Bearer '+token}});if(!r.ok){const data=await r.json();throw Error(data.error||'预览暂不可用');}const blob=await r.blob();if(selected!==t.job.id)return;if(previewURL)URL.revokeObjectURL(previewURL);previewURL=URL.createObjectURL(blob);$('preview').src=previewURL;$('preview').hidden=false;$('preview-empty').hidden=true;$('preview-caption').textContent=`第 ${latest.frame} 帧 · 已完整保存`;}catch(error){$('preview').hidden=true;$('preview-empty').hidden=false;$('preview-caption').textContent=error.message;}finally{previewBusy=false;}}
function renderSettings(data){$('blender-list').innerHTML=data.blenders.items.map(i=>`<div class="blender-row"><div><b>${escapeHTML(i.name)}</b><small>${escapeHTML(i.path)}</small></div>${i.id===data.blenders.default?'<span class="badge">默认版本</span>':`<button data-default="${i.id}">设为默认</button>`}<button data-remove="${i.id}">移除</button></div>`).join('')||'<p>尚未找到 Blender，请添加一个版本。</p>';$('pick-blender').hidden=!window.pywebview;$('watch-files').checked=data.watchdog.files;$('watch-recover').checked=data.watchdog.recover;$('watch-attempts').value=data.watchdog.attempts;$('watch-delay').value=data.watchdog.delay;$('watch-status').textContent=`正在监测 ${data.watchdog.watching} 个目录`+(data.watchdog.error?' · '+data.watchdog.error:'');for(const k of ['server','port','name'])$('frpc-'+k).value=data.frpc[k];$('frpc-remote-port').value=data.frpc.remote_port;$('frpc-autostart').checked=data.frpc.autostart;$('frpc-start').disabled=data.frpc.running;$('frpc-stop').disabled=!data.frpc.running;$('frpc-status').textContent=(data.frpc.running?'进程运行中':'未运行')+' · '+(data.frpc.message||'填写并保存服务器设置后启动');$('frpc-log').textContent=data.frpc.log||'尚无连接日志';}
$('blender-form').onsubmit=guard(async e=>{e.preventDefault();await command('blender.save',{path:$('blender-path').value.trim(),name:$('blender-name').value.trim()});$('blender-form').reset();await loadSettings();toast('Blender 版本已保存');});
$('blender-list').onclick=guard(async e=>{const b=e.target.closest('button');if(!b)return;await command('blender.save',b.dataset.default?{default:b.dataset.default}:{remove:b.dataset.remove});await loadSettings();});
$('pick-blender').onclick=guard(async()=>{const path=await window.pywebview.api.pick('blender');if(path)$('blender-path').value=path;});
$('watchdog-form').onsubmit=guard(async e=>{e.preventDefault();await command('watchdog.save',{files:$('watch-files').checked,recover:$('watch-recover').checked,attempts:Number($('watch-attempts').value),delay:Number($('watch-delay').value)});await loadSettings();toast('Watchdog 设置已保存');});
$('save-key').onclick=guard(async()=>{const value=$('manual-key').value;const data=await api('access',{token:value});token=data.token;sessionStorage.setItem('renderdesk-token',token);$('manual-key').value='';toast('新密钥已生效，其他设备需要重新连接');});
$('frpc-form').onsubmit=guard(async e=>{e.preventDefault();await command('frpc.save',{server:$('frpc-server').value.trim(),port:Number($('frpc-port').value),remote_port:Number($('frpc-remote-port').value),name:$('frpc-name').value.trim(),token:$('frpc-token').value,autostart:$('frpc-autostart').checked});$('frpc-token').value='';await loadSettings();toast('frpc 连接设置已保存');});
for(const action of ['start','stop'])$('frpc-'+action).onclick=guard(async()=>{await command('frpc.'+action);await loadSettings();});
setInterval(async()=>{if($('settings-view').hidden||!token||$('login').open)return;try{const data=await api('settings');$('frpc-log').textContent=data.frpc.log||'尚无连接日志';$('frpc-status').textContent=(data.frpc.running?'进程运行中':'未运行')+' · '+(data.frpc.message||'');$('frpc-start').disabled=data.frpc.running;$('frpc-stop').disabled=!data.frpc.running;}catch{}},4000);

function localDate(timestamp){if(!timestamp)return '';const date=new Date(timestamp*1000);return new Date(date-date.getTimezoneOffset()*60000).toISOString().slice(0,16);}
$('schedule').onclick=()=>{const job=snapshot.tasks.find(t=>t.job.id===selected).job;for(const k of ['start_at','pause_at'])$('schedule-form').elements[k].value=localDate(job[k]);$('schedule-dialog').showModal();};$('schedule-form').onsubmit=guard(async e=>{e.preventDefault();const values={id:selected};for(const k of ['start_at','pause_at'])values[k]=e.target.elements[k].value?new Date(e.target.elements[k].value).getTime()/1000:null;await command('schedule',values);$('schedule-dialog').close();toast('定时计划已保存');});
if(!token)$('login').showModal();poll();setInterval(poll,1600);
