'use strict';
const $ = id => document.getElementById(id);
const escapeHTML = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels = {ready:'等待开始',starting:'启动中',loading:'载入工程',rendering:'正在渲染',pausing:'等待当前帧保存',watching:'等待完整 PNG',paused:'已暂停 · 资源已释放',finishing:'正在退出进程',complete:'全部完成',interrupted:'已中断 · 可继续',error:'发生错误'};
let token = new URLSearchParams(location.hash.slice(1)).get('token') || sessionStorage.getItem('renderdesk-token') || '';
if(location.hash) history.replaceState(null,'',location.pathname);
let snapshot = {tasks:[],processes:[],system:{}}, selected = null, cursor = -1, logGeneration = 0, attachProcess = null, polling = false, settingsLoaded = false;
let toastTimer;
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,5000);}
function duration(seconds){if(seconds==null)return '—';seconds=Math.max(0,Math.floor(seconds));return `${Math.floor(seconds/3600).toString().padStart(2,'0')}:${Math.floor(seconds/60)%60}`.replace(/:(\d)$/,':0$1')+':'+String(seconds%60).padStart(2,'0');}
const number=(value,unit='')=>value==null?'—':Number(value).toFixed(1)+unit;
async function api(path,body){const r=await fetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});const data=await r.json();if(r.status===401){sessionStorage.removeItem('renderdesk-token');if(!$('login').open)$('login').showModal();throw Error('请输入有效访问密钥');}if(!r.ok)throw Error(data.error||'请求失败');return data;}
async function command(action,values={}){const {operation}=await api('commands',{action,values});for(let i=0;i<900;i++){await new Promise(resolve=>setTimeout(resolve,300));const result=await api('operations/'+operation);if(result.done){if(result.error)throw Error(result.error);await poll();return result.result;}}throw Error('操作仍在后台处理，请刷新查看状态，不要重复提交。');}
function guard(fn){return async event=>{const button=event?.submitter||event?.currentTarget;const disable=button?.tagName==='BUTTON';if(disable)button.disabled=true;try{await fn(event);}catch(error){toast(error.message);}finally{if(disable)button.disabled=false;renderDetail();}};}
function setView(view){for(const v of ['tasks','processes','settings'])$(v+'-view').hidden=v!==view;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const titles={tasks:['渲染工作台','让渲染继续，也给生活留一点时间。'],processes:['本机进程','把藏在后台的渲染，看清楚、管起来。'],settings:['连接与通知','无论在哪，都能知道渲染进行到了哪里。']};$('page-title').textContent=titles[view][0];$('page-description').textContent=titles[view][1];if(view==='settings')loadSettings().catch(e=>toast(e.message));}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));
function taskMarkup({job:j,status:s}){const percent=Math.min(100,Math.round(100*s.done/(s.total||1)));return `<article class="task-card ${selected===j.id?'selected':''}" tabindex="0" role="button" data-task="${escapeHTML(j.id)}" aria-label="选择 ${escapeHTML(j.name)}"><div class="task-top"><div><div class="task-name">${escapeHTML(j.name)}</div><div class="task-path" title="${escapeHTML(j.blend)}">${escapeHTML(j.blend)}</div></div><span class="badge ${s.state==='error'?'error':''}">${escapeHTML(labels[s.state]||s.state)}</span></div><div class="task-metrics"><span><b>${s.done} / ${s.total}</b> 帧 · ${percent}%</span><span>用时 <b>${duration(s.elapsed)}</b></span><span>CPU <b>${number(s.cpu,'%')}</b></span><span>内存 <b>${number(s.ram_mb,' MB')}</b></span><span>GPU <b>${number(s.gpu,'%')}</b></span><span>显存 <b>${number(s.vram_mb,' MB')}</b></span></div><div class="progress"><i style="width:${percent}%"></i></div></article>`;}
function render(){const tasks=snapshot.tasks;let running=tasks.filter(t=>t.status.running).length;const done=tasks.reduce((n,t)=>n+t.status.done,0),total=tasks.reduce((n,t)=>n+t.status.total,0);$('task-count').textContent=tasks.length;$('running').innerHTML=running+'<small>个任务</small>';$('frames').innerHTML=done+'<small>/ '+total+'</small>';$('cpu').innerHTML=number(snapshot.system.cpu)+'<small>%</small>';$('memory').innerHTML=number(snapshot.system.ram_used)+`<small>/ ${number(snapshot.system.ram_total)} GB</small>`;$('queue-summary').textContent=tasks.length+' 个任务 · '+running+' 个运行中';
const list=$('tasks'), previousScroll=list.scrollTop;const cards=tasks.map(taskMarkup).join('');if(!tasks.length){list.innerHTML='<div class="empty"><div class="symbol">◈</div><h3>从一帧灵感开始</h3><p>添加 Blender 工程，让后台渲染有一个看得见的工作台。</p><button class="primary" id="empty-add">＋ 添加第一个任务</button></div>';$('empty-add').onclick=()=>openTask();}else{for(const t of tasks){let card=list.querySelector(`[data-task="${CSS.escape(t.job.id)}"]`);const html=taskMarkup(t);if(!card){if(list.querySelector('.empty'))list.textContent='';list.insertAdjacentHTML('beforeend',html);}else if(card.outerHTML!==html){const focused=document.activeElement===card;card.outerHTML=html;if(focused)list.querySelector(`[data-task="${CSS.escape(t.job.id)}"]`).focus({preventScroll:true});}}}list.scrollTop=previousScroll;
$('processes').innerHTML=snapshot.processes.map(p=>{const managed=tasks.find(t=>t.status.pid===p.pid);return `<tr><td>${escapeHTML(p.blend.split(/[\\/]/).pop()||'Blender')}<small>PID ${p.pid}</small></td><td>${duration(p.elapsed)}</td><td>${number(p.cpu,'%')}</td><td>${number(p.ram_mb,' MB')}</td><td>${number(p.gpu,'%')}<small>${number(p.vram_mb,' MB')}</small></td><td><button data-process="${p.pid}" ${managed?'disabled':''}>${managed?'已管理':'接入任务'}</button></td></tr>`;}).join('')||'<tr><td colspan="6" class="muted">暂未发现运行中的 Blender 进程。</td></tr>';
const notices=snapshot.notices||[];$('notice').hidden=!notices.length;$('notice').textContent=notices.join(' · ');renderDetail();if(snapshot.bark){const status={pending:'等待发送 / 重试中',sent:'最近一条通知已发送',failed:'最近一条通知失败（已尝试 3 次）'};$('bark-status').textContent=(status[snapshot.bark.last_status]||'尚无通知记录')+'。通知需要管理服务保持运行。';}}
function selectTask(id){selected=id;cursor=-1;logGeneration++;$('log').textContent='';render();pollLog();}
$('tasks').onclick=e=>{const card=e.target.closest('[data-task]');if(card)selectTask(card.dataset.task);};$('tasks').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){const card=e.target.closest('[data-task]');if(card){e.preventDefault();selectTask(card.dataset.task);}}};
function renderDetail(){const t=snapshot.tasks.find(t=>t.job.id===selected);for(const id of ['start','pause','schedule','copy-output'])$(id).disabled=!t;if(!t)return;const j=t.job,s=t.status;$('detail-title').textContent=j.name;$('detail-state').textContent=labels[s.state]||s.state;$('start').disabled=s.running;$('pause').disabled=!s.running;$('detail-info').textContent=`${s.done} / ${s.total} 帧 · 当前帧 ${s.frame??'—'} · 累计 ${duration(s.elapsed)} · 预计剩余 ${duration(s.eta)}\n输出：${j.output}`+(s.message?' · '+s.message:'')+(j.start_at?' · 计划开始 '+new Date(j.start_at*1000).toLocaleString():'')+(j.pause_at?' · 计划暂停 '+new Date(j.pause_at*1000).toLocaleString():'');}
async function pollLog(){if(!selected)return;const id=selected,generation=logGeneration;const result=await api('jobs/'+encodeURIComponent(id)+'/log?cursor='+cursor);if(id!==selected||generation!==logGeneration)return;cursor=result.cursor;const log=$('log');if(result.reset)log.textContent='';if(result.text)log.textContent=(log.textContent+result.text).slice(-160000);if($('follow').checked)log.scrollTop=log.scrollHeight;}
async function poll(){if(polling||!token)return;polling=true;try{snapshot=await api('state');sessionStorage.setItem('renderdesk-token',token);$('connection').textContent='服务已连接 · 实时更新';if($('login').open)$('login').close();if(!selected&&snapshot.tasks.length)selectTask(snapshot.tasks[0].job.id);render();await pollLog();document.documentElement.dataset.ready='true';}catch(error){$('connection').textContent='连接中断 · 自动重连';}finally{polling=false;}}
$('login-form').onsubmit=async e=>{e.preventDefault();token=$('access-key').value.trim();try{await api('state');$('login-error').textContent='';await poll();}catch(error){$('login-error').textContent=error.message;}};
$('refresh').onclick=guard(async()=>{await command('refresh');toast('列表已刷新');});$('start').onclick=guard(()=>command('start',{id:selected}));$('pause').onclick=guard(async()=>{await command('pause',{id:selected});toast('已请求暂停，等待当前帧完整保存。');});
async function copy(value){try{await navigator.clipboard.writeText(value);toast('已复制');}catch{const input=document.createElement('textarea');input.value=value;document.body.append(input);input.select();const ok=document.execCommand('copy');input.remove();if(!ok)throw Error('浏览器不允许复制，请使用 HTTPS 或在桌面端复制');toast('已复制');}}
$('copy-output').onclick=guard(()=>copy(snapshot.tasks.find(t=>t.job.id===selected).job.output));$('clear-log').onclick=()=>{$('log').textContent='';};
async function loadSettings(){const data=await api('settings');$('bark-enabled').checked=data.bark.enabled;$('bark-configured').textContent=data.bark.configured?'已保存推送地址；留空保留原地址':'尚未配置';$('remote-enabled').checked=data.remote_next;$('remote-port').value=data.port;$('remote-status').textContent=data.remote?'当前允许局域网访问；所有操作均需访问密钥。':'当前仅本机访问。启用并重启后可从局域网连接。';settingsLoaded=true;return data;}
$('bark-form').onsubmit=guard(async e=>{e.preventDefault();await command('bark.save',{enabled:$('bark-enabled').checked,url:$('bark-url').value.trim()});$('bark-url').value='';await loadSettings();toast('通知设置已保存');});$('bark-test').onclick=guard(async()=>{await command('bark.test');toast('测试通知已进入发送队列');});
$('remote-form').onsubmit=guard(async e=>{e.preventDefault();const r=await api('remote',{enabled:$('remote-enabled').checked,port:Number($('remote-port').value)});toast(r.message);});$('copy-key').onclick=guard(async()=>copy((await api('access')).token));
async function openTask(process=null){attachProcess=process;const form=$('task-form');form.reset();$('new-fields').hidden=!!process;for(const name of ['blend','blender'])form.elements[name].required=!process;$('pattern-field').hidden=!process;$('task-dialog-title').textContent=process?'接入进程 · PID '+process.pid:'新建渲染任务';$('task-help').textContent=process?'确认该进程真实的 PNG 输出目录、帧范围与命名。原脚本必须可重复执行；首次暂停可能丢弃刚开始的下一帧计算。':'路径均指渲染电脑上的文件。桌面端可使用“浏览”选择。';if(!process){try{const settings=await api('settings');form.elements.blender.value=settings.blenders[0]||'';}catch{}}document.querySelectorAll('[data-pick]').forEach(b=>b.hidden=!window.pywebview);$('task-dialog').showModal();}
$('new-task').onclick=guard(()=>openTask());$('processes').onclick=guard(async e=>{const b=e.target.closest('[data-process]');if(b)await openTask(snapshot.processes.find(p=>p.pid===Number(b.dataset.process)));});document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());document.querySelectorAll('[data-pick]').forEach(b=>b.onclick=guard(async()=>{const value=await window.pywebview.api.pick(b.dataset.pick);if(value)$('task-form').elements[b.dataset.pick].value=value;}));
$('task-form').onsubmit=guard(async e=>{e.preventDefault();const form=e.target,values=Object.fromEntries(new FormData(form));for(const k of ['start','end','step','threads'])values[k]=Number(values[k]);values.autoexec=form.elements.autoexec.checked;const id=await command(attachProcess?'attach':'add',attachProcess?{...values,process:attachProcess}:values);$('task-dialog').close();setView('tasks');selectTask(id);toast(attachProcess?'进程已接入':'任务已创建，点击开始即可渲染');});
function localDate(timestamp){if(!timestamp)return '';const date=new Date(timestamp*1000);return new Date(date-date.getTimezoneOffset()*60000).toISOString().slice(0,16);}
$('schedule').onclick=()=>{const job=snapshot.tasks.find(t=>t.job.id===selected).job;for(const k of ['start_at','pause_at'])$('schedule-form').elements[k].value=localDate(job[k]);$('schedule-dialog').showModal();};$('schedule-form').onsubmit=guard(async e=>{e.preventDefault();const values={id:selected};for(const k of ['start_at','pause_at'])values[k]=e.target.elements[k].value?new Date(e.target.elements[k].value).getTime()/1000:null;await command('schedule',values);$('schedule-dialog').close();toast('定时计划已保存');});
if(!token)$('login').showModal();poll();setInterval(poll,1600);
